<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions 
	xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:tns="urn:sendSMSwsdl"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="urn:sendSMSwsdl">
	<types>
		<xsd:schema targetNamespace="urn:sendSMSwsdl">
			<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
			<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
		</xsd:schema>
	</types>
	<message name="sendSMSRequest">
		<part name="user" type="xsd:string" />
		<part name="pass" type="xsd:string" />
		<part name="from" type="xsd:string" />
		<part name="target" type="xsd:string" />
		<part name="mess" type="xsd:string" />
		<part name="lang" type="xsd:string" />
		<part name="expire" type="xsd:string" />
		<part name="shceduled" type="xsd:string" />
	</message>
	<message name="sendSMSResponse">
		<part name="return" type="xsd:string" />
	</message>
	<portType name="sendSMSwsdlPortType">
		<operation name="sendSMS">
			<documentation>SMS Sender</documentation>
			<input message="tns:sendSMSRequest"/>
			<output message="tns:sendSMSResponse"/>
		</operation>
	</portType>
	<binding name="sendSMSwsdlBinding" type="tns:sendSMSwsdlPortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="sendSMS">
			<soap:operation soapAction="http://localhost/service/" style="rpc"/>
			<input>
				<soap:body use="encoded" namespace="http://localhost/service/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="http://localhost/service/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="sendSMSwsdl">
		<port name="sendSMSwsdlPort" binding="tns:sendSMSwsdlBinding">
			<soap:address location="__URL__"/>
		</port>
	</service>
</definitions>